# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrea D'Angelo
title: PhD Student in Computer Science @ University of L'Aquila
email: andrea.dangelo6@graduate.univaq.it

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: _ad1411
github_username:  dangeloandrea14
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: _andreadng
linkedin_username: andrea-d-angelo-02569319a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Hello, I'm Andrea, a second year PhD student in Computer Science at the University of L’Aquila, Italy. 

    I previously earned my Bachelor’s and Master’s degrees in Computer Science in 2019 and 2022, respectively. 

    My research interests revolve around <mark>Natural Language Processing</mark>, <mark>Data Mining</mark>, and <mark>Large Language Models</mark>. 

content:
  - title: My Research
    layout: text
    content: | # this will include new lines to allow paragraphs
          <style>
                  ul#menu {
            font-family: Verdana, sans-serif;
            font-size: 11px;
            margin: 0;
            padding: 0;
            list-style: none;
            }
        ul#menu li {
            background-color: #FF831C;
            border-bottom: 5px solid #54BAE2;
            display: block;
            width: 150px;
            height: 30px;
            margin: 2px;
            float: left; /* elementi su singola riga */
            }
        ul#menu li a {
            color: #fff;
            display: block;
            font-weight: bold;
            line-height: 30px;
            text-decoration: none;
            width: 150px;
            height: 30px;
            text-align: center;
            }
        ul#menu li.active, ul#menu li:hover {
            background-color: #54BAE2;
            border-bottom: 5px solid #FF831C;
            }
          </style>
          <ul id="menu">
            <li><a href="#">Home</a></li>
            <li class="active"><a href="#">About Us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Portfolio</a></li>
            <li><a href="#">Contact</a></li>
          </ul>

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
